name: Tests

on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install dependencies on Linux/MacOS
        run: |
          conda info
          conda install -c conda-forge pocl pyopencl
          python -c 'import pyopencl as cl'
        if: ${{ runner.os != 'Windows' }}
      - name: Install dependencies
        run: |
          conda info
          conda install -c conda-forge numpy cython
          python -m pip install -r requirements.txt
          python -m pip install -e ".[dev]"
      - name: Run tests
        run: |
          python -m pytest -v -m 'not slow or slow'
